---
- hosts: all
  become: true
  tasks: 

  - name: update repository index
    ansible.builtin.apt:
      update_cache: yes

  - name: remove apache2 package
    ansible.builtin.apt:
      name: apache2
      state: absent

  - name: remove support for php
    ansible.builtin.apt:
      name: libapache2-mod-php 
      state: absent

  - name: remove htop
    ansible.builtin.apt:
     name: htop
     state: absent
